//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListaProjekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TabelaLista
    {
        public int id { get; set; }
        public string imiePierwsze { get; set; }
        public string imieDrugie { get; set; }
        public string nazwisko { get; set; }
        public string nazwiskoRodowe { get; set; }
        public string ulica { get; set; }
        public string numerDomu { get; set; }
        public string numerMieszkania { get; set; }
        public string kod { get; set; }
        public string miasto { get; set; }
        public Nullable<System.DateTime> dataUrodzenia { get; set; }
        public string miejsceUrodzenia { get; set; }
        public string pesel { get; set; }
        public string nip { get; set; }
        public string imieOjca { get; set; }
        public string imieMatki { get; set; }
        public string nazwiskoMatki { get; set; }
        public string plec { get; set; }
        public string dokumentTyp { get; set; }
        public string dokumentWydany { get; set; }
        public string dokumentNumer { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string wyksztalcenie { get; set; }
        public string obywatelstwo { get; set; }
        public string narodowosc { get; set; }
    }
}
